// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using main.Services.Storage;

#nullable disable

namespace main.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("main.Models.Favourite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Favourites");
                });

            modelBuilder.Entity("main.Models.PriceHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateRecorded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("PriceHistories");
                });

            modelBuilder.Entity("main.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<string>("ProductURL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductURL")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasDiscriminator<int>("Type");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("main.Models.CPU", b =>
                {
                    b.HasBaseType("main.Models.Product");

                    b.Property<int>("Cores")
                        .HasColumnType("integer");

                    b.Property<string>("Socket")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("Products", t =>
                        {
                            t.Property("Socket")
                                .HasColumnName("CPU_Socket");
                        });

                    b.HasDiscriminator().HasValue(398);
                });

            modelBuilder.Entity("main.Models.GPU", b =>
                {
                    b.HasBaseType("main.Models.Product");

                    b.Property<int>("Memory")
                        .HasColumnType("integer");

                    b.Property<string>("Memorytype")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue(397);
                });

            modelBuilder.Entity("main.Models.HDD", b =>
                {
                    b.HasBaseType("main.Models.Product");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("FormFactor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("Products", t =>
                        {
                            t.Property("FormFactor")
                                .HasColumnName("HDD_FormFactor");
                        });

                    b.HasDiscriminator().HasValue(399);
                });

            modelBuilder.Entity("main.Models.Motherboard", b =>
                {
                    b.HasBaseType("main.Models.Product");

                    b.Property<string>("Cpu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FormFactor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ram")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Socket")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue(400);
                });

            modelBuilder.Entity("main.Models.RAM", b =>
                {
                    b.HasBaseType("main.Models.Product");

                    b.Property<int>("Frequency")
                        .HasColumnType("integer");

                    b.Property<int>("Memory")
                        .HasColumnType("integer");

                    b.Property<string>("MemoryType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("Products", t =>
                        {
                            t.Property("Memory")
                                .HasColumnName("RAM_Memory");
                        });

                    b.HasDiscriminator().HasValue(403);
                });

            modelBuilder.Entity("main.Models.SSD", b =>
                {
                    b.HasBaseType("main.Models.Product");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.ToTable("Products", t =>
                        {
                            t.Property("Capacity")
                                .HasColumnName("SSD_Capacity");
                        });

                    b.HasDiscriminator().HasValue(407);
                });

            modelBuilder.Entity("main.Models.Favourite", b =>
                {
                    b.HasOne("main.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("main.Models.PriceHistory", b =>
                {
                    b.HasOne("main.Models.Product", "Product")
                        .WithMany("PriceHistories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("main.Models.Product", b =>
                {
                    b.Navigation("PriceHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
